//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zodiac_Finder.serviceRef_NameByDate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceRef_NameByDate.webSvc_NameByDateSoap")]
    public interface webSvc_NameByDateSoap {
        
        // CODEGEN: Generating message contract since element name FindZodiacByDateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindZodiacByDate", ReplyAction="*")]
        Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse FindZodiacByDate(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindZodiacByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse> FindZodiacByDateAsync(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindZodiacByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindZodiacByDate", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequestBody Body;
        
        public FindZodiacByDateRequest() {
        }
        
        public FindZodiacByDateRequest(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindZodiacByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int day;
        
        public FindZodiacByDateRequestBody() {
        }
        
        public FindZodiacByDateRequestBody(int mth, int day) {
            this.mth = mth;
            this.day = day;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindZodiacByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindZodiacByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponseBody Body;
        
        public FindZodiacByDateResponse() {
        }
        
        public FindZodiacByDateResponse(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindZodiacByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindZodiacByDateResult;
        
        public FindZodiacByDateResponseBody() {
        }
        
        public FindZodiacByDateResponseBody(string FindZodiacByDateResult) {
            this.FindZodiacByDateResult = FindZodiacByDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webSvc_NameByDateSoapChannel : Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webSvc_NameByDateSoapClient : System.ServiceModel.ClientBase<Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap>, Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap {
        
        public webSvc_NameByDateSoapClient() {
        }
        
        public webSvc_NameByDateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webSvc_NameByDateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_NameByDateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_NameByDateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap.FindZodiacByDate(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest request) {
            return base.Channel.FindZodiacByDate(request);
        }
        
        public string FindZodiacByDate(int mth, int day) {
            Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest inValue = new Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequestBody();
            inValue.Body.mth = mth;
            inValue.Body.day = day;
            Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse retVal = ((Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap)(this)).FindZodiacByDate(inValue);
            return retVal.Body.FindZodiacByDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse> Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap.FindZodiacByDateAsync(Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest request) {
            return base.Channel.FindZodiacByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateResponse> FindZodiacByDateAsync(int mth, int day) {
            Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest inValue = new Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_NameByDate.FindZodiacByDateRequestBody();
            inValue.Body.mth = mth;
            inValue.Body.day = day;
            return ((Zodiac_Finder.serviceRef_NameByDate.webSvc_NameByDateSoap)(this)).FindZodiacByDateAsync(inValue);
        }
    }
}
