//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zodiac_Finder.serviceRef_PostcodeFinder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap")]
    public interface webSvc_PostcodeFinderSoap {
        
        // CODEGEN: Generating message contract since element name dropSuburb from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeFinder", ReplyAction="*")]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse PostcodeFinder(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeFinder", ReplyAction="*")]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> PostcodeFinderAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeFinderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeFinder", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody Body;
        
        public PostcodeFinderRequest() {
        }
        
        public PostcodeFinderRequest(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostcodeFinderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dropSuburb;
        
        public PostcodeFinderRequestBody() {
        }
        
        public PostcodeFinderRequestBody(string dropSuburb) {
            this.dropSuburb = dropSuburb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeFinderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeFinderResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponseBody Body;
        
        public PostcodeFinderResponse() {
        }
        
        public PostcodeFinderResponse(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostcodeFinderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostcodeFinderResult;
        
        public PostcodeFinderResponseBody() {
        }
        
        public PostcodeFinderResponseBody(string PostcodeFinderResult) {
            this.PostcodeFinderResult = PostcodeFinderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webSvc_PostcodeFinderSoapChannel : Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webSvc_PostcodeFinderSoapClient : System.ServiceModel.ClientBase<Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap>, Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap {
        
        public webSvc_PostcodeFinderSoapClient() {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_PostcodeFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeFinder(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request) {
            return base.Channel.PostcodeFinder(request);
        }
        
        public string PostcodeFinder(string dropSuburb) {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody();
            inValue.Body.dropSuburb = dropSuburb;
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse retVal = ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeFinder(inValue);
            return retVal.Body.PostcodeFinderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeFinderAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request) {
            return base.Channel.PostcodeFinderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> PostcodeFinderAsync(string dropSuburb) {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody();
            inValue.Body.dropSuburb = dropSuburb;
            return ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeFinderAsync(inValue);
        }
    }
}
