//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zodiac_Finder.serviceRef_PostcodeFinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap")]
    public interface webSvc_PostcodeFinderSoap {
        
        // CODEGEN: Generating message contract since element name SuburbListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuburbList", ReplyAction="*")]
        Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse SuburbList(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuburbList", ReplyAction="*")]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse> SuburbListAsync(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest request);
        
        // CODEGEN: Generating message contract since element name PostcodeListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeList", ReplyAction="*")]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse PostcodeList(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeList", ReplyAction="*")]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse> PostcodeListAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest request);
        
        // CODEGEN: Generating message contract since element name dropSuburb from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeFinder", ReplyAction="*")]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse PostcodeFinder(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostcodeFinder", ReplyAction="*")]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> PostcodeFinderAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuburbListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuburbList", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequestBody Body;
        
        public SuburbListRequest() {
        }
        
        public SuburbListRequest(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SuburbListRequestBody {
        
        public SuburbListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuburbListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuburbListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponseBody Body;
        
        public SuburbListResponse() {
        }
        
        public SuburbListResponse(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SuburbListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString SuburbListResult;
        
        public SuburbListResponseBody() {
        }
        
        public SuburbListResponseBody(Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString SuburbListResult) {
            this.SuburbListResult = SuburbListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeList", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequestBody Body;
        
        public PostcodeListRequest() {
        }
        
        public PostcodeListRequest(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostcodeListRequestBody {
        
        public PostcodeListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponseBody Body;
        
        public PostcodeListResponse() {
        }
        
        public PostcodeListResponse(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostcodeListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString PostcodeListResult;
        
        public PostcodeListResponseBody() {
        }
        
        public PostcodeListResponseBody(Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString PostcodeListResult) {
            this.PostcodeListResult = PostcodeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeFinderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeFinder", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody Body;
        
        public PostcodeFinderRequest() {
        }
        
        public PostcodeFinderRequest(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostcodeFinderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dropSuburb;
        
        public PostcodeFinderRequestBody() {
        }
        
        public PostcodeFinderRequestBody(string dropSuburb) {
            this.dropSuburb = dropSuburb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostcodeFinderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostcodeFinderResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponseBody Body;
        
        public PostcodeFinderResponse() {
        }
        
        public PostcodeFinderResponse(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostcodeFinderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostcodeFinderResult;
        
        public PostcodeFinderResponseBody() {
        }
        
        public PostcodeFinderResponseBody(string PostcodeFinderResult) {
            this.PostcodeFinderResult = PostcodeFinderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webSvc_PostcodeFinderSoapChannel : Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webSvc_PostcodeFinderSoapClient : System.ServiceModel.ClientBase<Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap>, Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap {
        
        public webSvc_PostcodeFinderSoapClient() {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_PostcodeFinderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webSvc_PostcodeFinderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.SuburbList(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest request) {
            return base.Channel.SuburbList(request);
        }
        
        public Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString SuburbList() {
            Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequestBody();
            Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse retVal = ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).SuburbList(inValue);
            return retVal.Body.SuburbListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse> Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.SuburbListAsync(Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest request) {
            return base.Channel.SuburbListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListResponse> SuburbListAsync() {
            Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.SuburbListRequestBody();
            return ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).SuburbListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeList(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest request) {
            return base.Channel.PostcodeList(request);
        }
        
        public Zodiac_Finder.serviceRef_PostcodeFinder.ArrayOfString PostcodeList() {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequestBody();
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse retVal = ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeList(inValue);
            return retVal.Body.PostcodeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse> Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeListAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest request) {
            return base.Channel.PostcodeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListResponse> PostcodeListAsync() {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeListRequestBody();
            return ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeFinder(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request) {
            return base.Channel.PostcodeFinder(request);
        }
        
        public string PostcodeFinder(string dropSuburb) {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody();
            inValue.Body.dropSuburb = dropSuburb;
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse retVal = ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeFinder(inValue);
            return retVal.Body.PostcodeFinderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap.PostcodeFinderAsync(Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest request) {
            return base.Channel.PostcodeFinderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderResponse> PostcodeFinderAsync(string dropSuburb) {
            Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest inValue = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequest();
            inValue.Body = new Zodiac_Finder.serviceRef_PostcodeFinder.PostcodeFinderRequestBody();
            inValue.Body.dropSuburb = dropSuburb;
            return ((Zodiac_Finder.serviceRef_PostcodeFinder.webSvc_PostcodeFinderSoap)(this)).PostcodeFinderAsync(inValue);
        }
    }
}
